# Generated by Django 5.0.6 on 2024-06-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('nombreUsuario', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=40)),
                ('numero', models.IntegerField(max_length=9)),
                ('correo', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=20)),
                ('fechacreacion', models.DateField(verbose_name='Fecha creacion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsound.rol')),
            ],
        ),
    ]
