# Generated by Django 5.0.6 on 2024-07-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0003_alter_usuario_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Artista')),
                ('nombreArtista', models.CharField(max_length=100)),
                ('biografiaArtista', models.TextField()),
                ('discografiaArtista', models.TextField()),
                ('recopilatorioArtista', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Evento')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('descripcion', models.TextField()),
                ('video_presentacion', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_telefonico',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Número Telefónico (+56)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechacreacion',
            field=models.DateField(verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id de usuario'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='rsound.artista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='rsound.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_artistas/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='rsound.artista')),
            ],
        ),
    ]
