# Generated by Django 5.0.6 on 2024-07-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0004_artista_evento_remove_usuario_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechacreacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
