# Generated by Django 5.0.6 on 2024-07-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0005_alter_usuario_fechacreacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
