# Generated by Django 5.0.6 on 2024-07-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0006_delete_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
