# Generated by Django 5.0.6 on 2024-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0007_artista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='rsound'),
        ),
    ]
