# Generated by Django 5.0.6 on 2024-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsound', '0008_alter_artista_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Noticia')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField(verbose_name='Fecha de Publicación')),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('descripcion', models.TextField()),
                ('video_presentacion', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
